name: Trade
main: main.Trade
version: 0.0.1-SANPSHOT
author: B0WL
api-version: 1.13
depend: [Vault]

commands:
  Auction:
    description: auction
    usage: /<command>  
  Test:
    description: test
    permission: auction.manager
    usage: /<command> <nbt|eco>
    
permissions:
  auction.user:
    default: true
  auction.manager:
    default: op